### ISSUE TITLE
error in the browser console, [ sendRemoveListener on closed conduit ]

### ISSUE THREAD

**Issue by MelchiorGaspar** [breadgrocery/download-manager#10]
I found the following error for your addon when used in 
- Firefox v133.0.3 and 
- Firefox addon v1.0.10

Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped. [popup.html:7:28](moz-extension://12b0e8eb-3346-469c-9007-0486f8a2843a/popup.html)

Unknown pseudo-class or pseudo-element ‘-ms-reveal’.  Ruleset ignored due to bad selector. [popup.html:151:44](moz-extension://12b0e8eb-3346-469c-9007-0486f8a2843a/popup.html)

Unknown pseudo-class or pseudo-element ‘moz-focus-inner’.  Ruleset ignored due to bad selector. [popup.html:128:11](moz-extension://12b0e8eb-3346-469c-9007-0486f8a2843a/popup.html)

sendRemoveListener on closed conduit download-manager@breadgrocery.github.com.549755816520 [ConduitsChild.sys.mjs:122:13](resource://gre/modules/ConduitsChild.sys.mjs)
    _send resource://gre/modules/ConduitsChild.sys.mjs:122
    removeListener resource://gre/modules/ExtensionChild.sys.mjs:688
    removeListener resource://gre/modules/ExtensionChild.sys.mjs:944
    register chrome://extensions/content/child/ext-storage.js:165
    removeListener resource://gre/modules/ExtensionCommon.sys.mjs:2980
    revoke resource://gre/modules/ExtensionCommon.sys.mjs:3002
    close resource://gre/modules/ExtensionCommon.sys.mjs:3007
    unload resource://gre/modules/ExtensionCommon.sys.mjs:1038
    unload resource://gre/modules/ExtensionPageChild.sys.mjs:280
    unload resource://gre/modules/ExtensionPageChild.sys.mjs:323
    destroyExtensionContext resource://gre/modules/ExtensionPageChild.sys.mjs:495
    observe resource://gre/modules/ExtensionPageChild.sys.mjs:396

something to fix I take it lol ..
good luck..
and I am happy I can bug report for you.

it happens when I click on the icon to open the popup sub-window for your download manager.

**Comment by breadgrocery** [comment]
You might have enabled the css option in the console panel. The -webkit-, -ms, and moz- prefixes are used for different browsers. These are expected behaviors, as this is a multi-browser extension.

As for `sendRemoveListener on closed conduit`, I couldn't reproduce it on my computer.
But I find [sendRemoveListener on closed conduit errors spams the console](https://bugzilla.mozilla.org/show_bug.cgi?id=1633315).

Mozilla’s responsiveness is pretty slow,probably something to do with their market share. Issues lingering for ages, plugins left unreviewed... maybe they’re short on staff, who knows huh? 

Kinda disappointing. But luckily, Firefox isn’t my flavor. lol.

**Comment by MelchiorGaspar** [comment]
sry I was sleeping. for my late reply.
aah so not an issue with your addon?
ooh well.

**Comment by MelchiorGaspar** [comment]
So your addon work is primarily for Google Chrome?
what else do you do for addons or programming?

**Comment by breadgrocery** [comment]
> So your addon work is primarily for Google Chrome?

Basically, yes.

> what else do you do for addons or programming?

It's mostly driven by personal interests, kinda diverse. Have gotten into GUI programming recently.

**Comment by MelchiorGaspar** [comment]
ooh ok.


> > So your addon work is primarily for Google Chrome?
> 
> Basically, yes.
ooh ok.


> > what else do you do for addons or programming?
> 
> It's mostly driven by personal interests, do whatever comes to mind. Have gotten into GUI programming recently.

nice GUI programming kool.
what programming languages do you know?

Can we chat here or do you recommend a different place to chat?
Like a Discord APP server or email?

I have a temperature converter console app I wrote originally for class assignment in college 2001-2002
programming in C and adv. C way back then... I was in Data structures in C back then in year 2 but my life belly up then.. 
so I was unable to finish college.

I ported my temperature converter console app from C to C++ easily enough...
in the past year or so I got it to compile in Microsoft visual studios 2022 community ed.
huwayy!! and it now has a solution and project file for it. and all is well I added a rc resource file for version info and an icon.

I really want to make a GUI in C++/.NET/ or QT6 maybe.
sadly I don't know anything about GUI programming except I have barely heard of handles...

**Comment by breadgrocery** [comment]
> Like a Discord APP server or email?

Wrap it up here before this issue turns into a nove lol. 
Hit me up at breadgrocery@gmail.com if you wanna chat. 

I'm a newbie in GUI programming, and I've been exploring WPF development in C# recently, you know, interests for personal tools.

**Comment by MelchiorGaspar** [comment]
ok I will email you then with my above post
using my gmail account.
